name: Build & Test

on:
    push:
        branches: [ "main", "dev" ]

    pull_request:
        branches: [ "main", "dev" ]

jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: |
                      6.x.x
                      7.x.x
                      8.x.x

            - name: Run
              shell: pwsh
              run: ".\\Excellence.Pipelines\\Scripts\\ContinuousIntegration\\Run.ps1"
