name: Continuous Integration

on:
    push:
        branches: [ "main", "dev", "release" ]

    pull_request:
        branches: [ "main", "dev", "release" ]

jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install .NET 6
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.x.x

            - name: Install .NET 7
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.x.x

            - name: Install .NET 8
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.x.x

            - name: Run
              shell: pwsh
              run: ".\\Excellence.Pipelines\\Scripts\\ContinuousIntegration\\Run.ps1"
